apiVersion: v1
kind: Service
metadata:
  name: {{ SERVICE_NAME }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ DOMAIN }}"
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  type: ClusterIP
  selector:
    name: {{ LABEL_NAME }}
  clusterIP: None
  ports:
    {% for port in PORTS %}
    - port: {{ port }}
      targetPort: {{ port }}
    {% endfor %}
