apiVersion: v1
kind: Service
metadata:
  name: {{ SERVICE_NAME }}
spec:
  type: NodePort
  selector:
    name: {{ LABEL_NAME }}
  ports:
    {% for port in PORTS %}
    - port: {{ port }}
      targetPort: {{ port }}
    {% endfor %}
