apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ STATEFULSET_NAME }}
spec:
  selector:
    matchLabels:
      name: {{ LABEL_NAME }}
  serviceName: {{ SERVICE_NAME }}
  template:
    metadata:
      labels:
       name: {{ LABEL_NAME }}
    spec:
      initContainers:
        - name: create-config
          image: {{ IMAGE_NAME }}:{{ IMAGE_TAG }}
          command:
            - bash
            - "-c"
            - |
              set -ex;
              mkdir -p {{ DATABASE_LOG_DIR }};
              touch {{ DATABASE_LOG_FULL_PATH }}
              chown -R mongodb:mongodb {{ DATABASE_LOG_DIR }};
              {{ INIT_CONTAINER_CREATE_CONFIG_COMMANDS }}
          volumeMounts:
            - name: {{ VOLUME_NAME }}
              mountPath: {{ VOLUME_PATH_ROOT }}
            - name: {{ VOLUME_NAME }}
              mountPath: {{ VOLUME_PATH_DB }}
              subPath: {{ VOLUME_SUBPATH_DB|default("db", true) }}
            - name: {{ VOLUME_NAME }}
              mountPath: {{ VOLUME_PATH_CONFIGDB }}
              subPath: {{ VOLUME_SUBPATH_CONFIGDB|default("configdb", true) }}
            - name: mongodb-config-map
              mountPath: {{ CONFIG_MAP_MOUNT_PATH }}
      containers:
        - name: {{ CONTAINER_NAME|default("dbaas-container", true) }}
          image: {{ IMAGE_NAME }}:{{ IMAGE_TAG }}
          imagePullPolicy: "Always"
          args:
            - "--config"
            - "{{ DATABASE_CONFIG_FULL_PATH }}"
          ports:
            - containerPort: {{ CONTAINER_PORT }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ INIT_USER }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ INIT_PASSWORD }}
            - name: MONGO_INITDB_DATABASE
              value: admin
            - name: MONGODB_ADMINDBAAS_USER
              value: admindbaas
            - name: MONGODB_ADMINDBAAS_PASSWORD
              value: tmp_initial_pwd
            - name: MONGODB_BACKUP_USER
              value: backup
            - name: MONGODB_BACKUP_PASSWORD
              value: tmp_initial_pwd
            - name: MONGODB_DB_ARQ_USER
              value: db_arq
            - name: MONGODB_DB_ARQ_PASSWORD
              value: tmp_initial_pwd
            - name: MONGODB_ZABBIX_USER
              value: usr_zabbix
            - name: MONGODB_ZABBIX__PASSWORD
              value: tmp_initial_pwd
            - name: MONGODB_TELEGRAF_USER
              value: usr_telegraf
            - name: MONGODB_TELEGRAF_PASSWORD
              value: tmp_initial_pwd
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POOL_DOMAIN
              value: "{{ POOL_DOMAIN }}"
            - name: CHECK_DNS
              value: "true"
          volumeMounts:
            - name: {{ VOLUME_NAME }}
              mountPath: {{ VOLUME_PATH_ROOT }}
            - name: {{ VOLUME_NAME }}
              mountPath: {{ VOLUME_PATH_DB }}
              subPath: {{ VOLUME_SUBPATH_DB|default("db", true) }}
            - name: {{ VOLUME_NAME }}
              mountPath: {{ VOLUME_PATH_CONFIGDB }}
              subPath: {{ VOLUME_SUBPATH_CONFIGDB|default("configdb", true) }}
            - name: mongodb-config-map
              mountPath: {{ CONFIG_MAP_MOUNT_PATH }}
          resources:
            requests:
              cpu: {{ CPU }}m
              memory: {{ MEMORY }}Mi
            limits:
              cpu: {{ CPU_LIMIT }}m
              memory: {{  MEMORY_LIMIT }}Mi
        - name: database-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -f {{ DATABASE_LOG_FULL_PATH }}']
          volumeMounts:
            - name: {{ VOLUME_NAME }}
              mountPath: {{ VOLUME_PATH_ROOT }}
      volumes:
        - name: {{ VOLUME_NAME }}
          persistentVolumeClaim:
            claimName: {{ VOLUME_CLAIM_NAME }}
        - name: mongodb-config-map
          configMap:
            name: {{ CONFIG_MAP_NAME }}
