language: python
python:
  - 3.6.1
services:
  - mongodb
  - mysql
script:
  - make test
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS host_provider;'
  - make db_initialize
install:
  - pip install -r requirements_dev.txt
notifications:
  email: false