
workflows:
  - ./host_provider/workflow/steps

libraries: []

celery:
  broker_url: redis://localhost:6379/0
  result_backend: redis://localhost:6379/0
  worker_concurrency: 8
  result_expires: 0
  worker_send_task_events: True
  worker_prefetch_multiplier: 1

signal:
  host: localhost
  port: 6379
  password: null
  database: 0
  polling_time: 0.5

store:
  host: localhost
  port: 27017
  database: workflow
  username: null
  password: null
  auth_source: admin
  auth_mechanism: null
  connect_timeout: 30000

graph:
  workflow_polling_time: 0.5
  dag_polling_time: 0.5

cli:
  time_format: '%d/%m/%Y %H:%M:%S'

extensions: {}

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    verbose:
      format: '[%(asctime)s][%(levelname)s] %(name)s %(filename)s:%(funcName)s:%(lineno)d | %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'
    simple:
      (): 'colorlog.ColoredFormatter'
      format: '%(log_color)s[%(asctime)s][%(levelname)s] %(blue)s%(processName)s%(reset)s | %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
  loggers:
    celery:
      handlers:
        - console
      level: INFO

    root:
      handlers:
        - console
      level: INFO
    