name: Run Tests

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    name: Test
    steps:
      - name: setup python verision
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.7' ## USED ONLY IN CI
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: "4.4.3"
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install apt dependencies
        run: sudo apt update && sudo apt install -y libmysqlclient-dev gcc &&  pip install --upgrade setuptools &&  pip install --upgrade wheel
      - name: Cache dependency
        uses: actions/cache@v2
        id: cachepip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements_dev.txt') }}
      - name: Install Requirements
        run: pip install -r requirements_dev.txt
      - name: Run Tests
        run: make test
      - name: Send to codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittests 
          name: codecov-umbrella 
          fail_ci_if_error: true 
          verbose: true 